# SPDX-FileCopyrightText: 2014 2014 Emma Prest, <emma@occrp.org> et al.
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aleph
description: Helm chart for Aleph
type: application
version: 3.12.4
appVersion: 3.12.4
