# SPDX-FileCopyrightText: 2014 2014 Emma Prest, <emma@occrp.org> et al.
#
# SPDX-License-Identifier: MIT

"apiVersion": "v1"
"kind": "Namespace"
"metadata":
  "name": "dev"
  "labels":
    "name": "dev"
---
"apiVersion": "v1"
"kind": "Namespace"
"metadata":
  "name": "staging"
  "labels":
    "name": "staging"
