# SPDX-FileCopyrightText: 2014 2014 Emma Prest, <emma@occrp.org> et al.
#
# SPDX-License-Identifier: MIT

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.global.namingPrefix }}-aleph-config
data:
  {{- toYaml .Values.global.commonEnv | nindent 2}}
  {{- toYaml .Values.global.env | nindent 2}}
